// Code generated by scripts/gen-agent-protocol from src/agent/catalogue.ts.
// DO NOT EDIT. Run `./scripts/gen-agent-protocol` after changing the catalogue;
// CI runs it with --check, so a stale copy here fails the build.
//
// This file is DATA. The validation that uses it is in validate.go, hand-written,
// because ADR 0004 wants the agent checking arguments independently rather than
// trusting a control plane it must assume is compromised.
package protocol

// ArgumentKind is how one argument is validated. Mirrors ArgumentKind in the
// TypeScript catalogue; both sides implement these rules and no others.
type ArgumentKind struct {
	// GoType is "string", "int64" or "bool".
	GoType string
	// Pattern is an RE2 pattern, anchored, or empty when the kind is not
	// identifier-shaped. RE2 is why the catalogue forbids lookahead: a pattern
	// using it would compile in the control plane and fail here.
	Pattern string
	// MaxBytes is the longest accepted value; 0 means no limit applies (bool).
	MaxBytes int
	// Min and Max bound a number. Meaningful only when Bounded is true, because
	// 0 is a legitimate bound and an absent bound must not read as one.
	Min     int64
	Max     int64
	Bounded bool
	// OneOf is the complete accepted set, or nil.
	OneOf []string
	// Validator names the parser that must accept this value before it is acted
	// on, or is empty. A kind with a validator is inert data until then.
	Validator string
	// Why this kind exists, carried across so the agent's own source explains
	// itself without a reader needing the TypeScript.
	Why string
}

// ArgumentKinds is the complete argument vocabulary.
//
// There is no "text", "string", "args", "command", "flags" or "env" kind, and
// that absence is acceptance 3 of RL-M2-002: no operation can accept a free-form
// command because no kind can express one. A test in each language fails if one
// is added.
var ArgumentKinds = map[string]ArgumentKind{
	"site_slug":        {GoType: "string", Pattern: "^[a-z0-9](?:[a-z0-9-]{0,30}[a-z0-9])?$", MaxBytes: 32, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "", Why: "one slug is simultaneously a Linux user, a directory and part of a unit name"},
	"service_id":       {GoType: "string", Pattern: "^rl-[a-z0-9](?:[a-z0-9-]{0,46}[a-z0-9])?$", MaxBytes: 50, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "", Why: "the rl- prefix is what makes 'restart a service' unable to name sshd"},
	"package_name":     {GoType: "string", Pattern: "^[a-z0-9][a-z0-9+.-]{1,62}$", MaxBytes: 64, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "", Why: "distribution package names, narrower than dpkg allows and deliberately so"},
	"path_in_site":     {GoType: "string", Pattern: "^[a-zA-Z0-9_-]+(?:\\.[a-zA-Z0-9_-]+)*(?:/[a-zA-Z0-9_-]+(?:\\.[a-zA-Z0-9_-]+)*)*$", MaxBytes: 255, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "", Why: "a path the agent may write inside a site it owns; privd re-resolves it anyway"},
	"port":             {GoType: "int64", Pattern: "", MaxBytes: 0, Min: 1, Max: 65535, Bounded: true, OneOf: nil, Validator: "", Why: "a TCP port, bounded so an out-of-range value is refused before it reaches a config"},
	"runtime":          {GoType: "string", Pattern: "", MaxBytes: 16, Min: 0, Max: 0, Bounded: false, OneOf: []string{"node", "python", "static", "php", "ruby"}, Validator: "", Why: "which runtime a site needs, from a closed set rather than a name to look up"},
	"service_action":   {GoType: "string", Pattern: "", MaxBytes: 16, Min: 0, Max: 0, Bounded: false, OneOf: []string{"start", "stop", "restart", "reload"}, Validator: "", Why: "the four things that can be done to a unit, enumerated so there is no fifth"},
	"enabled":          {GoType: "bool", Pattern: "", MaxBytes: 0, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "", Why: "a flag, for operations whose only variation is on or off"},
	"unit_file":        {GoType: "string", Pattern: "", MaxBytes: 16384, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "systemd-analyze-verify", Why: "a systemd unit, inert until systemd itself parses it without complaint"},
	"webserver_config": {GoType: "string", Pattern: "", MaxBytes: 65536, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "nginx-t", Why: "a server block, inert until the web server's own parser accepts it"},
	"sudoers_fragment": {GoType: "string", Pattern: "", MaxBytes: 4096, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "visudo-c", Why: "a sudoers.d fragment; ADR 0004 requires visudo -c to pass before install"},
	"certificate_pem":  {GoType: "string", Pattern: "", MaxBytes: 32768, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "x509", Why: "a certificate chain, parsed as X.509 before it is written anywhere"},
	"private_key_pem":  {GoType: "string", Pattern: "", MaxBytes: 16384, Min: 0, Max: 0, Bounded: false, OneOf: nil, Validator: "pkcs8", Why: "a private key, parsed before install and never logged"},
}

// ArgumentSpec is one argument of one operation. Every argument is required;
// there is no defaulting, so nothing is ever implied by an omission.
type ArgumentSpec struct {
	Name string
	Kind string
}

// Operation is one thing the agent can be asked to do.
type Operation struct {
	Name string
	// Performer is "agent" or "privd". The agent refuses to perform a privd
	// operation itself rather than attempting it and failing on permissions,
	// because the second is indistinguishable from a misconfigured host.
	Performer string
	Args      []ArgumentSpec
	Summary   string
	// Idempotent records whether running this twice equals running it once.
	// M2's exit criteria include an idempotent second run, and it is a property
	// of each operation rather than of the runner.
	Idempotent bool
}

// Operations is the complete catalogue. An operation absent from this slice is
// refused by Lookup with no default branch (ADR 0002).
var Operations = []Operation{
	{Name: "host.inventory.collect", Performer: "agent", Args: nil, Summary: "Report this host's distribution, kernel, memory, disks and installed runtimes", Idempotent: true},
	{Name: "host.health.report", Performer: "agent", Args: nil, Summary: "Report load, memory pressure, disk headroom and clock skew", Idempotent: true},
	{Name: "site.user.create", Performer: "privd", Args: []ArgumentSpec{{Name: "slug", Kind: "site_slug"}}, Summary: "Create the Linux user and home directory a site runs as", Idempotent: true},
	{Name: "site.user.remove", Performer: "privd", Args: []ArgumentSpec{{Name: "slug", Kind: "site_slug"}}, Summary: "Remove a site's Linux user and its home directory", Idempotent: false},
	{Name: "site.file.write", Performer: "agent", Args: []ArgumentSpec{{Name: "slug", Kind: "site_slug"}, {Name: "path", Kind: "path_in_site"}}, Summary: "Write a file inside a site directory the agent owns", Idempotent: true},
	{Name: "service.unit.install", Performer: "privd", Args: []ArgumentSpec{{Name: "service", Kind: "service_id"}, {Name: "unit", Kind: "unit_file"}}, Summary: "Install a systemd unit and reload the manager", Idempotent: true},
	{Name: "service.control", Performer: "privd", Args: []ArgumentSpec{{Name: "service", Kind: "service_id"}, {Name: "action", Kind: "service_action"}}, Summary: "Start, stop, restart or reload a Ratline service", Idempotent: false},
	{Name: "service.enable", Performer: "privd", Args: []ArgumentSpec{{Name: "service", Kind: "service_id"}, {Name: "enabled", Kind: "enabled"}}, Summary: "Set whether a Ratline service starts at boot", Idempotent: true},
	{Name: "webserver.config.install", Performer: "privd", Args: []ArgumentSpec{{Name: "slug", Kind: "site_slug"}, {Name: "config", Kind: "webserver_config"}}, Summary: "Install a site's web server configuration and reload it", Idempotent: true},
	{Name: "webserver.certificate.install", Performer: "privd", Args: []ArgumentSpec{{Name: "slug", Kind: "site_slug"}, {Name: "certificate", Kind: "certificate_pem"}, {Name: "key", Kind: "private_key_pem"}}, Summary: "Install a certificate and its key with root ownership and mode 0600", Idempotent: true},
	{Name: "package.install", Performer: "privd", Args: []ArgumentSpec{{Name: "package", Kind: "package_name"}}, Summary: "Install a package from the distribution's repositories", Idempotent: true},
	{Name: "sudoers.fragment.install", Performer: "privd", Args: []ArgumentSpec{{Name: "slug", Kind: "site_slug"}, {Name: "fragment", Kind: "sudoers_fragment"}}, Summary: "Install a sudoers.d fragment, after visudo -c accepts it", Idempotent: true},
	{Name: "runtime.provision", Performer: "privd", Args: []ArgumentSpec{{Name: "runtime", Kind: "runtime"}, {Name: "port", Kind: "port"}}, Summary: "Make a runtime available on this host and reserve its port", Idempotent: true},
}
