#!/usr/bin/env node --experimental-strip-types
/**
 * Generate the agent's copy of the operation catalogue (RL-M2-002).
 *
 *   ./scripts/gen-agent-protocol           write agent/internal/protocol/catalogue_gen.go
 *   ./scripts/gen-agent-protocol --check   fail if it would change
 *
 * Acceptance 2 says the two sides "cannot drift". A generator alone does not
 * achieve that — it makes them AGREE at the moment somebody remembers to run it.
 * `--check` in CI is the part that makes the claim true, by turning a stale
 * generated file into a red build instead of a silent disagreement between a
 * control plane that signs an instruction and an agent that refuses it.
 *
 * Data only. Every compiled regexp, every bounds test, every parser invocation
 * lives in the hand-written validate.go beside it, because generated code nobody
 * reads is a poor place for security logic — and because ADR 0004 wants the agent
 * validating independently, which means its checking code is its own.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { ARGUMENT_KINDS, KINDS, OPERATIONS } from "../src/agent/catalogue.ts";


const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TARGET = join(ROOT, "agent", "internal", "protocol", "catalogue_gen.go");

/** A Go string literal. Backticks are avoided so no value can end the literal. */
const goString = (value: string): string => JSON.stringify(value);

function render(): string {
  const lines: string[] = [];
  const out = (line = "") => lines.push(line);

  out("// Code generated by scripts/gen-agent-protocol from src/agent/catalogue.ts.");
  out("// DO NOT EDIT. Run `./scripts/gen-agent-protocol` after changing the catalogue;");
  out("// CI runs it with --check, so a stale copy here fails the build.");
  out("//");
  out("// This file is DATA. The validation that uses it is in validate.go, hand-written,");
  out("// because ADR 0004 wants the agent checking arguments independently rather than");
  out("// trusting a control plane it must assume is compromised.");
  out("package protocol");
  out();

  // --- kinds ---------------------------------------------------------------
  out("// ArgumentKind is how one argument is validated. Mirrors ArgumentKind in the");
  out("// TypeScript catalogue; both sides implement these rules and no others.");
  out("type ArgumentKind struct {");
  out("\t// GoType is \"string\", \"int64\" or \"bool\".");
  out("\tGoType string");
  out("\t// Pattern is an RE2 pattern, anchored, or empty when the kind is not");
  out("\t// identifier-shaped. RE2 is why the catalogue forbids lookahead: a pattern");
  out("\t// using it would compile in the control plane and fail here.");
  out("\tPattern string");
  out("\t// MaxBytes is the longest accepted value; 0 means no limit applies (bool).");
  out("\tMaxBytes int");
  out("\t// Min and Max bound a number. Meaningful only when Bounded is true, because");
  out("\t// 0 is a legitimate bound and an absent bound must not read as one.");
  out("\tMin      int64");
  out("\tMax      int64");
  out("\tBounded  bool");
  out("\t// OneOf is the complete accepted set, or nil.");
  out("\tOneOf []string");
  out("\t// Validator names the parser that must accept this value before it is acted");
  out("\t// on, or is empty. A kind with a validator is inert data until then.");
  out("\tValidator string");
  out("\t// Why this kind exists, carried across so the agent's own source explains");
  out("\t// itself without a reader needing the TypeScript.");
  out("\tWhy string");
  out("}");
  out();

  out("// ArgumentKinds is the complete argument vocabulary.");
  out("//");
  out("// There is no \"text\", \"string\", \"args\", \"command\", \"flags\" or \"env\" kind, and");
  out("// that absence is acceptance 3 of RL-M2-002: no operation can accept a free-form");
  out("// command because no kind can express one. A test in each language fails if one");
  out("// is added.");
  out("var ArgumentKinds = map[string]ArgumentKind{");
  for (const [name, kind] of Object.entries(KINDS)) {
    const bounded = kind.min !== undefined || kind.max !== undefined;
    const fields = [
      `GoType: ${goString(kind.goType)}`,
      `Pattern: ${goString(kind.pattern ?? "")}`,
      `MaxBytes: ${String(kind.maxBytes ?? 0)}`,
      `Min: ${String(kind.min ?? 0)}`,
      `Max: ${String(kind.max ?? 0)}`,
      `Bounded: ${String(bounded)}`,
      kind.oneOf === undefined
        ? "OneOf: nil"
        : `OneOf: []string{${kind.oneOf.map(goString).join(", ")}}`,
      `Validator: ${goString(kind.validator ?? "")}`,
      `Why: ${goString(kind.why)}`,
    ];
    out(`\t${goString(name)}: {${fields.join(", ")}},`);
  }
  out("}");
  out();

  // --- operations ----------------------------------------------------------
  out("// ArgumentSpec is one argument of one operation. Every argument is required;");
  out("// there is no defaulting, so nothing is ever implied by an omission.");
  out("type ArgumentSpec struct {");
  out("\tName string");
  out("\tKind string");
  out("}");
  out();
  out("// Operation is one thing the agent can be asked to do.");
  out("type Operation struct {");
  out("\tName string");
  out("\t// Performer is \"agent\" or \"privd\". The agent refuses to perform a privd");
  out("\t// operation itself rather than attempting it and failing on permissions,");
  out("\t// because the second is indistinguishable from a misconfigured host.");
  out("\tPerformer string");
  out("\tArgs      []ArgumentSpec");
  out("\tSummary   string");
  out("\t// Idempotent records whether running this twice equals running it once.");
  out("\t// M2's exit criteria include an idempotent second run, and it is a property");
  out("\t// of each operation rather than of the runner.");
  out("\tIdempotent bool");
  out("}");
  out();
  out("// Operations is the complete catalogue. An operation absent from this slice is");
  out("// refused by Lookup with no default branch (ADR 0002).");
  out("var Operations = []Operation{");
  for (const operation of OPERATIONS) {
    const args =
      operation.args.length === 0
        ? "nil"
        : `[]ArgumentSpec{${operation.args
            .map((a) => `{Name: ${goString(a.name)}, Kind: ${goString(a.kind)}}`)
            .join(", ")}}`;
    out(
      `\t{Name: ${goString(operation.name)}, Performer: ${goString(operation.performer)}, ` +
        `Args: ${args}, Summary: ${goString(operation.summary)}, ` +
        `Idempotent: ${String(operation.idempotent)}},`,
    );
  }
  out("}");
  out();

  return lines.join("\n");
}

function gofmt(source: string): string {
  try {
    // execFileSync with an argv array, never a shell string (C2). `gofmt` reads
    // stdin when given no file, so nothing touches the filesystem to format.
    return execFileSync("gofmt", [], { input: source, encoding: "utf8" });
  } catch (cause) {
    // A generator that emits unformattable Go has produced a syntax error, and
    // writing it out would turn a clear failure here into a confusing one in the
    // Go build. Refuse instead.
    throw new Error(
      `gofmt rejected the generated source, which means this generator emitted invalid Go. ` +
        `Nothing was written.`,
      { cause },
    );
  }
}

const generated = gofmt(render());

if (process.argv.includes("--check")) {
  let existing: string;
  try {
    existing = readFileSync(TARGET, "utf8");
  } catch {
    console.error(
      `agent/internal/protocol/catalogue_gen.go does not exist.\n` +
        `Run ./scripts/gen-agent-protocol and commit the result.`,
    );
    process.exit(1);
  }

  if (existing !== generated) {
    console.error(
      `agent/internal/protocol/catalogue_gen.go is out of date with ` +
        `src/agent/catalogue.ts.\n\n` +
        `This is the check that makes "the two sides cannot drift" true rather than\n` +
        `hopeful. Run ./scripts/gen-agent-protocol and commit the result.`,
    );
    process.exit(1);
  }

  console.log("catalogue_gen.go is current");
} else {
  writeFileSync(TARGET, generated, "utf8");
  console.log(
    `wrote agent/internal/protocol/catalogue_gen.go — ` +
      `${String(OPERATIONS.length)} operations, ` +
      `${String(Object.keys(ARGUMENT_KINDS).length)} argument kinds`,
  );
}
